// Banco de Opções
// Curated set of Exercicio records and OpcaoDeRefeicao content maintained
// manually (not generated by algorithm or AI). Consumed by Motor de Geração.
// TODO: populate with data from legacy/script.js in a future task
